version: "3.8"

networks:
  netSEN300.1:
    external: false

services:
  sqlserver.c:
    container_name: sqlserver.c
    #build:
      #context: ./
      #dockerfile: 3.dockerfile
    #image: sqlserver.c:1
    # the old way when I wasn't using a dockerfile
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1434:1433'
    networks:
      - netSEN300.1
    environment:
      SA_PASSWORD: 'abc123!!23'
      ACCEPT_EULA: 'Y'
  
  dotnet-api-card.1.c:
    container_name: dotnet-api-card.1.c
    build:
      context: ./
      dockerfile: CardAPI.dockerfile
    image: dotnet-api-card.1.c:1
    ports:
      - "9501:80"
    networks:
      - netSEN300.1
    depends_on:
      - sqlserver.c
      - eureka.c
      - redis.c
      - mongo.c
  
  eureka.c:
    container_name: eureka.c
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    networks:
      - netSEN300.1